# Site settings
title: NotesByMihuu
description: >-
  Personal notes and findings, mostly about technology (and sometimes other things).
  A space to document my journey and share insights.
baseurl: ""
url: "https://mihaistreames.github.io"
github_username: MihaiStreames

# SEO & Social
author:
  name: MihaiStreames
lang: en_US
twitter:
  card: summary_large_image

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
minima:
  skin: dark

# Excludes
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
